services:
  - type: web
    name: nearby-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server-working.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AWS_REGION
        value: ap-south-1
      - key: PORT
        value: 3000
